
import React, { useState } from 'react';
import { Pizza, Loader2, Eye, EyeOff, X, Mail, ArrowRight, CheckCircle, AlertTriangle, Database, Copy, FileCode } from 'lucide-react';
import { useAppContext } from '../contexts/AppContext';

// SQL Script for initial setup - UPDATED TO DISABLE RLS FOR INSTANT DATA ACCESS
const SUPABASE_SCHEMA_SQL = `
-- CREACIÓN DE TABLAS Y RELACIONES PARA RESTAURANTE PRO 2.0
-- Script Actualizado: DESHABILITA RLS e INCLUYE DATOS DE DEMOSTRACIÓN.

-- =============================================================================
-- 1. LIMPIEZA Y PREPARACIÓN
-- =============================================================================

DO $$ 
DECLARE 
    r RECORD; 
BEGIN 
    -- Eliminar políticas existentes para evitar conflictos
    FOR r IN (SELECT policyname, tablename FROM pg_policies WHERE schemaname = 'public') LOOP 
        EXECUTE 'DROP POLICY IF EXISTS "' || r.policyname || '" ON "' || r.tablename || '";'; 
    END LOOP; 
END $$;

-- =============================================================================
-- 2. CREACIÓN DE TABLAS (Si no existen)
-- =============================================================================

create table if not exists restaurants (
  id text primary key,
  settings jsonb not null default '{}'::jsonb,
  created_at timestamp with time zone default now()
);

create table if not exists app_users (
  id text primary key,
  restaurant_id text references restaurants(id) on delete cascade,
  nombre text not null,
  email text not null,
  rol text not null,
  avatar_url text,
  password text,
  estado_delivery text default 'DISPONIBLE',
  is_deleted boolean default false,
  must_change_password boolean default false,
  last_location jsonb,
  created_at timestamp with time zone default now()
);

create table if not exists categories (
  id text primary key,
  restaurant_id text references restaurants(id) on delete cascade,
  nombre text not null,
  orden integer default 0,
  created_at timestamp with time zone default now()
);

create table if not exists ingredients (
  id text primary key,
  restaurant_id text references restaurants(id) on delete cascade,
  nombre text not null,
  unidad text not null,
  stock_actual numeric default 0,
  stock_minimo numeric default 0,
  coste_unitario numeric default 0,
  categoria text default 'GENERAL',
  created_at timestamp with time zone default now()
);

create table if not exists menu_items (
  id text primary key,
  restaurant_id text references restaurants(id) on delete cascade,
  category_id text references categories(id) on delete set null,
  nombre text not null,
  descripcion text,
  precio_base numeric default 0,
  coste numeric default 0,
  receta jsonb default '[]'::jsonb,
  img_url text,
  etiquetas text[],
  disponible boolean default true,
  tiempo_preparacion_min integer default 0,
  stock_actual numeric,
  permite_venta_sin_stock boolean default false,
  is_deleted boolean default false,
  created_at timestamp with time zone default now()
);

create table if not exists customers (
  id text primary key,
  restaurant_id text references restaurants(id) on delete cascade,
  nombre text not null,
  telefono text,
  email text,
  ltv numeric default 0,
  ultima_compra timestamp with time zone,
  frecuencia_promedio_dias numeric default 0,
  is_verified boolean default false,
  direccion jsonb default '{}'::jsonb,
  is_deleted boolean default false,
  created_at timestamp with time zone default now()
);

create table if not exists tables (
  id text primary key,
  table_number integer,
  restaurant_id text references restaurants(id) on delete cascade,
  nombre text,
  estado text default 'LIBRE',
  x integer default 0,
  y integer default 0,
  shape text default 'square',
  order_id integer,
  mozo_id text,
  created_at timestamp with time zone default now()
);

create table if not exists orders (
  id bigint generated by default as identity primary key,
  restaurant_id text references restaurants(id) on delete cascade,
  customer_id text references customers(id) on delete set null,
  table_id integer,
  creado_por_id text,
  repartidor_id text,
  mozo_id text,
  tipo text not null,
  estado text not null,
  subtotal numeric default 0,
  descuento numeric default 0,
  impuestos numeric default 0,
  propina numeric default 0,
  total numeric default 0,
  items jsonb default '[]'::jsonb,
  payments jsonb default '[]'::jsonb,
  creado_en text,
  created_at timestamp with time zone default now()
);

create table if not exists coupons (
  id text primary key,
  restaurant_id text references restaurants(id) on delete cascade,
  codigo text not null,
  tipo text not null,
  valor numeric default 0,
  activo boolean default true,
  expira_en text,
  minimo_subtotal numeric,
  created_at timestamp with time zone default now()
);

-- Indices
create index if not exists idx_orders_restaurant on orders(restaurant_id);
create index if not exists idx_orders_customer on orders(customer_id);
create index if not exists idx_menu_items_restaurant on menu_items(restaurant_id);
create index if not exists idx_app_users_email on app_users(email);

-- =============================================================================
-- 3. SEGURIDAD: DESHABILITAR RLS (Solución para "No se ven los datos")
-- =============================================================================
ALTER TABLE restaurants DISABLE ROW LEVEL SECURITY;
ALTER TABLE app_users DISABLE ROW LEVEL SECURITY;
ALTER TABLE categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE ingredients DISABLE ROW LEVEL SECURITY;
ALTER TABLE menu_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE customers DISABLE ROW LEVEL SECURITY;
ALTER TABLE tables DISABLE ROW LEVEL SECURITY;
ALTER TABLE orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE coupons DISABLE ROW LEVEL SECURITY;

-- =============================================================================
-- 4. SEED DATA (DATOS DE DEMOSTRACIÓN)
-- =============================================================================

-- 4.1 Restaurante Demo
INSERT INTO restaurants (id, settings)
VALUES ('rest-demo', '{"nombre": "Restaurante Demo", "direccion": "Calle Falsa 123", "telefono": "555-1234", "logo_url": "https://via.placeholder.com/150", "horarios": "Lun-Dom 9am-11pm", "iva_rate": 21, "precios_con_iva": true, "propina_opciones": [10, 15, 20]}')
ON CONFLICT (id) DO NOTHING;

-- 4.2 Usuarios (Super Admin y Gerente Demo)
INSERT INTO app_users (id, restaurant_id, nombre, email, rol, password, avatar_url)
VALUES 
('user-super-admin', NULL, 'Super Admin', 'admin@restaurante.com', 'SUPER_ADMIN', '123456', 'https://i.pravatar.cc/150?u=super'),
('user-demo-admin', 'rest-demo', 'Gerente Demo', 'demo@restaurante.com', 'ADMIN', '123456', 'https://i.pravatar.cc/150?u=demo')
ON CONFLICT (id) DO NOTHING;
`;

const ForgotPasswordModal: React.FC<{ onClose: () => void }> = ({ onClose }) => {
    const { recoverPassword } = useAppContext();
    const [email, setEmail] = useState('');
    const [isLoading, setIsLoading] = useState(false);
    const [isSent, setIsSent] = useState(false);
    const [errorMessage, setErrorMessage] = useState<string | null>(null);
    const [tempPassword, setTempPassword] = useState<string | null>(null);

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!email) return;
        
        setIsLoading(true);
        setErrorMessage(null);
        
        try {
            const tempPass = await recoverPassword(email);
            setTempPassword(tempPass);
            setIsSent(true);
        } catch (error: any) {
            setErrorMessage(error.message || "Error al intentar recuperar la contraseña.");
        } finally {
            setIsLoading(false);
        }
    };

    return (
        <div className="fixed inset-0 bg-black/60 z-50 flex items-center justify-center p-4" onClick={onClose}>
            <div className="bg-white dark:bg-gray-800 rounded-lg shadow-xl w-full max-w-md p-6 relative" onClick={(e) => e.stopPropagation()}>
                <button onClick={onClose} className="absolute top-4 right-4 text-gray-400 hover:text-gray-600 dark:hover:text-gray-200">
                    <X className="h-5 w-5" />
                </button>

                {!isSent ? (
                    <>
                        <div className="mb-6 text-center">
                            <div className="mx-auto flex items-center justify-center h-12 w-12 rounded-full bg-orange-100 dark:bg-orange-900/30 mb-4">
                                <Mail className="h-6 w-6 text-orange-600 dark:text-orange-400" />
                            </div>
                            <h3 className="text-lg font-medium text-gray-900 dark:text-white">Recuperar Contraseña</h3>
                            <p className="text-sm text-gray-500 dark:text-gray-400 mt-2">
                                Ingresa tu correo electrónico y te enviaremos una contraseña temporal.
                            </p>
                        </div>
                        <form onSubmit={handleSubmit} className="space-y-4">
                            <div>
                                <label htmlFor="reset-email" className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                                    Email registrado
                                </label>
                                <input
                                    type="email"
                                    id="reset-email"
                                    value={email}
                                    onChange={(e) => setEmail(e.target.value)}
                                    className="block w-full px-3 py-2 text-sm bg-white dark:bg-gray-700 border border-gray-300 dark:border-gray-600 rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-orange-500"
                                    placeholder="ejemplo@restaurante.com"
                                    required
                                />
                            </div>
                            
                            {errorMessage && (
                                <div className="p-3 bg-red-100 dark:bg-red-900/30 text-red-700 dark:text-red-300 rounded-md text-sm flex items-center gap-2">
                                    <AlertTriangle className="h-4 w-4 shrink-0" />
                                    {errorMessage}
                                </div>
                            )}

                            <button
                                type="submit"
                                disabled={isLoading}
                                className="w-full flex justify-center items-center py-2.5 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-orange-600 hover:bg-orange-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-orange-500 disabled:opacity-50"
                            >
                                {isLoading ? <Loader2 className="h-4 w-4 animate-spin mr-2" /> : <ArrowRight className="h-4 w-4 mr-2" />}
                                {isLoading ? 'Procesando...' : 'Generar Contraseña Temporal'}
                            </button>
                        </form>
                    </>
                ) : (
                    <div className="text-center py-4">
                        <div className="mx-auto flex items-center justify-center h-12 w-12 rounded-full bg-green-100 dark:bg-green-900/30 mb-4 animate-bounce">
                            <CheckCircle className="h-6 w-6 text-green-600 dark:text-green-400" />
                        </div>
                        <h3 className="text-lg font-medium text-gray-900 dark:text-white">¡Contraseña Generada!</h3>
                        <p className="text-sm text-gray-500 dark:text-gray-400 mt-2 mb-4">
                            En producción, esto se enviaría por correo.
                        </p>
                        
                        {tempPassword && (
                            <div className="bg-gray-100 dark:bg-gray-700 p-4 rounded-lg mb-6 border border-gray-300 dark:border-gray-600">
                                <p className="text-xs text-gray-500 dark:text-gray-400 uppercase font-bold mb-1">Contraseña Temporal</p>
                                <p className="text-xl font-mono font-bold text-gray-900 dark:text-white tracking-wider select-all">{tempPassword}</p>
                            </div>
                        )}

                        <button
                            onClick={onClose}
                            className="w-full py-2 px-4 border border-gray-300 dark:border-gray-600 rounded-md text-sm font-medium text-gray-700 dark:text-gray-200 hover:bg-gray-50 dark:hover:bg-gray-700"
                        >
                            Volver
                        </button>
                    </div>
                )}
            </div>
        </div>
    );
};

const DatabaseSetupModal: React.FC<{ onClose: () => void }> = ({ onClose }) => {
    const { showToast } = useAppContext();

    const handleCopySql = () => {
        navigator.clipboard.writeText(SUPABASE_SCHEMA_SQL);
        showToast("Script SQL copiado al portapapeles.");
    };

    return (
        <div className="fixed inset-0 bg-black/60 z-50 flex items-center justify-center p-4" onClick={onClose}>
            <div className="bg-white dark:bg-gray-800 rounded-lg shadow-xl w-full max-w-2xl max-h-[90vh] flex flex-col" onClick={(e) => e.stopPropagation()}>
                <div className="p-4 border-b dark:border-gray-700 flex justify-between items-center">
                    <h3 className="font-bold text-lg text-gray-900 dark:text-white flex items-center gap-2">
                        <Database className="h-5 w-5 text-blue-500" /> Configuración de Base de Datos
                    </h3>
                    <button onClick={onClose} className="p-1 rounded-full hover:bg-gray-200 dark:hover:bg-gray-700"><X className="h-5 w-5" /></button>
                </div>
                <div className="p-6 overflow-y-auto">
                    <div className="bg-blue-50 dark:bg-blue-900/20 p-4 rounded-lg border border-blue-200 dark:border-blue-800 mb-4">
                        <p className="text-sm text-blue-800 dark:text-blue-300">
                            <strong>Instrucciones:</strong> Si no ves datos o no puedes iniciar sesión, ejecuta este script en el <strong>SQL Editor</strong> de Supabase. Este script <strong>DESHABILITA</strong> las políticas de seguridad (RLS) para asegurar que la app funcione inmediatamente sin conflictos de permisos y crea datos de demostración.
                        </p>
                        <ul className="list-disc list-inside text-sm text-blue-800 dark:text-blue-300 mt-2 ml-2">
                            <li>Usuario Admin: <strong>demo@restaurante.com</strong> (Clave: <strong>123456</strong>)</li>
                            <li>Usuario Super Admin: <strong>admin@restaurante.com</strong> (Clave: <strong>123456</strong>)</li>
                        </ul>
                    </div>
                    
                    <div className="relative">
                        <pre className="bg-gray-900 text-gray-100 p-4 rounded-lg text-xs font-mono overflow-x-auto h-64">
                            {SUPABASE_SCHEMA_SQL}
                        </pre>
                        <button 
                            onClick={handleCopySql}
                            className="absolute top-2 right-2 p-2 bg-white/10 hover:bg-white/20 rounded text-white flex items-center gap-1 text-xs"
                            title="Copiar SQL"
                        >
                            <Copy className="h-3 w-3" /> Copiar
                        </button>
                    </div>
                </div>
                <div className="p-4 bg-gray-50 dark:bg-gray-700/50 rounded-b-lg text-right">
                     <button onClick={onClose} className="px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-lg hover:bg-gray-50 dark:bg-gray-800 dark:text-gray-300 dark:border-gray-600 dark:hover:bg-gray-700">
                        Cerrar
                    </button>
                </div>
            </div>
        </div>
    );
};

export const LoginPage: React.FC = () => {
  const { login } = useAppContext();
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [showPassword, setShowPassword] = useState(false);
  const [isForgotModalOpen, setIsForgotModalOpen] = useState(false);
  const [isDbSetupOpen, setIsDbSetupOpen] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!email || !password) return;
    setIsLoading(true);

    await login(email, password);
    setIsLoading(false);
  };

  const inputClasses = "block w-full px-3 py-2 text-sm bg-white dark:bg-gray-700 border border-gray-300 dark:border-gray-600 rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-orange-500 focus:border-transparent";

  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-100 dark:bg-gray-900 p-4">
      <div className="w-full max-w-md p-8 space-y-6 bg-white dark:bg-gray-800 rounded-2xl shadow-xl relative">
        <div className="text-center">
            <div className="flex justify-center mb-4">
                <Pizza className="h-12 w-12 text-orange-500" />
            </div>
            <h1 className="text-3xl font-bold text-gray-900 dark:text-white">Bienvenido</h1>
            <p className="mt-2 text-gray-600 dark:text-gray-400">CRM Restaurante Pro</p>
            <div className="mt-4 inline-flex items-center gap-2 px-3 py-1 bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300 rounded-full text-xs font-semibold">
                <Database className="h-3 w-3" /> Supabase Conectado
            </div>
        </div>

        <form onSubmit={handleSubmit} className="space-y-6">
          <div>
            <label htmlFor="email" className="block text-sm font-medium text-gray-700 dark:text-gray-300">
              Email
            </label>
            <div className="mt-1">
              <input
                id="email"
                name="email"
                type="email"
                required
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                className={inputClasses}
                placeholder="admin@restaurante.com"
                disabled={isLoading}
              />
            </div>
          </div>

          <div>
            <label htmlFor="password" className="block text-sm font-medium text-gray-700 dark:text-gray-300">
              Contraseña
            </label>
            <div className="mt-1 relative">
              <input
                id="password"
                name="password"
                type={showPassword ? "text" : "password"}
                required
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                className={`${inputClasses} pr-10`}
                placeholder="••••••••"
                disabled={isLoading}
              />
              <button
                type="button"
                onClick={() => setShowPassword(!showPassword)}
                className="absolute inset-y-0 right-0 pr-3 flex items-center text-gray-400 hover:text-gray-600 dark:hover:text-gray-300 cursor-pointer"
              >
                {showPassword ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
              </button>
            </div>
          </div>

          <div className="flex items-center justify-between">
            <div className="text-sm">
              <button 
                type="button" 
                onClick={() => setIsForgotModalOpen(true)}
                className="font-medium text-orange-600 hover:text-orange-500 hover:underline"
              >
                ¿Olvidaste tu contraseña?
              </button>
            </div>
          </div>

          <div>
            <button
              type="submit"
              disabled={isLoading}
              className="w-full flex justify-center py-3 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-orange-600 hover:bg-orange-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-orange-500 disabled:bg-orange-400 disabled:cursor-not-allowed"
            >
              {isLoading ? (
                <>
                  <Loader2 className="animate-spin -ml-1 mr-3 h-5 w-5 text-white" />
                  Ingresando...
                </>
              ) : (
                'Iniciar Sesión'
              )}
            </button>
          </div>
        </form>
        
        {/* Database Setup Link */}
        <div className="mt-4 pt-4 border-t dark:border-gray-700 text-center">
            <button 
                onClick={() => setIsDbSetupOpen(true)}
                className="text-xs text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-200 flex items-center justify-center gap-1 w-full"
            >
                <FileCode className="h-3 w-3" /> Solución Problemas de Base de Datos (SQL)
            </button>
        </div>
      </div>
      
      {isForgotModalOpen && <ForgotPasswordModal onClose={() => setIsForgotModalOpen(false)} />}
      {isDbSetupOpen && <DatabaseSetupModal onClose={() => setIsDbSetupOpen(false)} />}
    </div>
  );
};
