
import React, { useState } from 'react';
import { Pizza, Eye, EyeOff, X, Mail, ArrowRight, CheckCircle, AlertTriangle, Database, Copy, FileCode, AlertCircle, Lock } from 'lucide-react';
import { useAppContext } from '../contexts/AppContext';
import { Button } from '../components/ui/Button';
import { Input } from '../components/ui/Input';

// SQL Script for initial setup - UPDATED FOR SECTORS & DELIVERY
const SUPABASE_SCHEMA_SQL = `
-- CREACIÓN DE TABLAS PARA RESTAURANTE PRO 2.0 - ACTUALIZADO
-- Incluye Sectores, Turnos y Estructura Avanzada

DO $$ 
DECLARE 
    r RECORD; 
BEGIN 
    -- Limpieza segura de políticas (RLS)
    FOR r IN (SELECT policyname, tablename FROM pg_policies WHERE schemaname = 'public') LOOP 
        EXECUTE 'DROP POLICY IF EXISTS "' || r.policyname || '" ON "' || r.tablename || '";'; 
    END LOOP; 
END $$;

create table if not exists restaurants (
  id text primary key,
  settings jsonb not null default '{}'::jsonb,
  created_at timestamp with time zone default now()
);

create table if not exists app_users (
  id text primary key,
  restaurant_id text references restaurants(id) on delete cascade,
  nombre text not null,
  email text not null,
  rol text not null,
  avatar_url text,
  password text,
  estado_delivery text default 'DISPONIBLE',
  is_deleted boolean default false,
  must_change_password boolean default false,
  last_location jsonb,
  created_at timestamp with time zone default now()
);

create table if not exists sectors (
  id text primary key,
  restaurant_id text references restaurants(id) on delete cascade,
  nombre text not null,
  orden integer default 0,
  is_active boolean default true,
  created_at timestamp with time zone default now()
);

create table if not exists categories (
  id text primary key,
  restaurant_id text references restaurants(id) on delete cascade,
  nombre text not null,
  orden integer default 0,
  parent_id text references categories(id) on delete cascade,
  created_at timestamp with time zone default now()
);

-- Migración: parent_id en categories
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'categories' AND column_name = 'parent_id') THEN 
        ALTER TABLE categories ADD COLUMN parent_id text references categories(id) on delete cascade; 
    END IF; 
END $$;

create table if not exists ingredients (
  id text primary key,
  restaurant_id text references restaurants(id) on delete cascade,
  nombre text not null,
  unidad text not null,
  stock_actual numeric default 0,
  stock_minimo numeric default 0,
  coste_unitario numeric default 0,
  categoria text default 'GENERAL',
  created_at timestamp with time zone default now()
);

create table if not exists menu_items (
  id text primary key,
  restaurant_id text references restaurants(id) on delete cascade,
  category_id text references categories(id) on delete set null,
  nombre text not null,
  descripcion text,
  precio_base numeric default 0,
  coste numeric default 0,
  receta jsonb default '[]'::jsonb,
  img_url text,
  etiquetas text[],
  disponible boolean default true,
  tiempo_preparacion_min integer default 0,
  stock_actual numeric,
  permite_venta_sin_stock boolean default false,
  is_deleted boolean default false,
  created_at timestamp with time zone default now()
);

create table if not exists customers (
  id text primary key,
  restaurant_id text references restaurants(id) on delete cascade,
  nombre text not null,
  telefono text,
  email text,
  ltv numeric default 0,
  ultima_compra timestamp with time zone,
  frecuencia_promedio_dias numeric default 0,
  is_verified boolean default false,
  direccion jsonb default '{}'::jsonb,
  is_deleted boolean default false,
  created_at timestamp with time zone default now()
);

create table if not exists tables (
  id text primary key,
  table_number integer,
  restaurant_id text references restaurants(id) on delete cascade,
  sector_id text references sectors(id) on delete set null,
  nombre text,
  estado text default 'LIBRE',
  x integer default 0,
  y integer default 0,
  shape text default 'square',
  order_id integer,
  mozo_id text,
  created_at timestamp with time zone default now()
);

-- Migración: sector_id en tables
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'tables' AND column_name = 'sector_id') THEN 
        ALTER TABLE tables ADD COLUMN sector_id text references sectors(id) on delete set null; 
    END IF; 
END $$;

create table if not exists orders (
  id bigint generated by default as identity primary key,
  restaurant_id text references restaurants(id) on delete cascade,
  customer_id text references customers(id) on delete set null,
  table_id integer,
  creado_por_id text,
  repartidor_id text,
  mozo_id text,
  tipo text not null,
  estado text not null,
  subtotal numeric default 0,
  descuento numeric default 0,
  impuestos numeric default 0,
  propina numeric default 0,
  total numeric default 0,
  items jsonb default '[]'::jsonb,
  payments jsonb default '[]'::jsonb,
  delivery_info jsonb default '{}'::jsonb,
  creado_en text,
  created_at timestamp with time zone default now()
);

-- Migración: delivery_info en orders
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'orders' AND column_name = 'delivery_info') THEN 
        ALTER TABLE orders ADD COLUMN delivery_info jsonb default '{}'::jsonb; 
    END IF; 
END $$;

create table if not exists coupons (
  id text primary key,
  restaurant_id text references restaurants(id) on delete cascade,
  codigo text not null,
  tipo text not null,
  valor numeric default 0,
  activo boolean default true,
  expira_en text,
  minimo_subtotal numeric,
  created_at timestamp with time zone default now()
);

-- Indices
create index if not exists idx_orders_restaurant on orders(restaurant_id);
create index if not exists idx_tables_sector on tables(sector_id);

-- DESHABILITAR RLS (MODO DESARROLLO ÁGIL)
ALTER TABLE restaurants DISABLE ROW LEVEL SECURITY;
ALTER TABLE app_users DISABLE ROW LEVEL SECURITY;
ALTER TABLE sectors DISABLE ROW LEVEL SECURITY;
ALTER TABLE categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE ingredients DISABLE ROW LEVEL SECURITY;
ALTER TABLE menu_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE customers DISABLE ROW LEVEL SECURITY;
ALTER TABLE tables DISABLE ROW LEVEL SECURITY;
ALTER TABLE orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE coupons DISABLE ROW LEVEL SECURITY;

-- SEED DATA (DEMO)
INSERT INTO restaurants (id, settings)
VALUES ('rest-demo', '{"nombre": "Restaurante Demo", "direccion": "Av. Siempre Viva 123", "telefono": "555-0100", "logo_url": "https://via.placeholder.com/150", "horarios": "Lun-Dom 9am-12pm", "iva_rate": 21, "precios_con_iva": true, "propina_opciones": [10, 15]}')
ON CONFLICT (id) DO NOTHING;

INSERT INTO sectors (id, restaurant_id, nombre, orden)
VALUES 
('sec-main', 'rest-demo', 'Salón Principal', 1),
('sec-terrace', 'rest-demo', 'Terraza', 2)
ON CONFLICT (id) DO NOTHING;

INSERT INTO app_users (id, restaurant_id, nombre, email, rol, password, avatar_url)
VALUES 
('user-super-admin', NULL, 'Super Admin', 'admin@restaurante.com', 'SUPER_ADMIN', '123456', 'https://i.pravatar.cc/150?u=super'),
('user-demo-mgr', 'rest-demo', 'Gerente Demo', 'demo@restaurante.com', 'GERENTE', '123456', 'https://i.pravatar.cc/150?u=mgr'),
('user-demo-waiter', 'rest-demo', 'Mozo Juan', 'juan@restaurante.com', 'MOZO/A', '123456', 'https://i.pravatar.cc/150?u=waiter'),
('user-demo-driver', 'rest-demo', 'Repartidor Pedro', 'pedro@restaurante.com', 'REPARTO', '123456', 'https://i.pravatar.cc/150?u=driver'),
('user-demo-cashier', 'rest-demo', 'Cajero Luis', 'caja@restaurante.com', 'CAJA', '123456', 'https://i.pravatar.cc/150?u=cash')
ON CONFLICT (id) DO NOTHING;
`;

const ForgotPasswordModal: React.FC<{ onClose: () => void }> = ({ onClose }) => {
    const { recoverPassword } = useAppContext();
    const [email, setEmail] = useState('');
    const [isLoading, setIsLoading] = useState(false);
    const [isSent, setIsSent] = useState(false);
    const [errorMessage, setErrorMessage] = useState<string | null>(null);
    const [tempPassword, setTempPassword] = useState<string | null>(null);

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!email) return;
        
        setIsLoading(true);
        setErrorMessage(null);
        
        try {
            const tempPass = await recoverPassword(email);
            setTempPassword(tempPass);
            setIsSent(true);
        } catch (error: any) {
            setErrorMessage(error.message || "Error al intentar recuperar la contraseña.");
        } finally {
            setIsLoading(false);
        }
    };

    return (
        <div className="fixed inset-0 bg-black/60 z-50 flex items-center justify-center p-4" onClick={onClose}>
            <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-2xl w-full max-w-md p-8 relative border border-gray-100 dark:border-gray-700" onClick={(e) => e.stopPropagation()}>
                <button onClick={onClose} className="absolute top-4 right-4 text-gray-400 hover:text-gray-600 dark:hover:text-gray-200 transition-colors">
                    <X className="h-5 w-5" />
                </button>

                {!isSent ? (
                    <>
                        <div className="mb-8 text-center">
                            <div className="mx-auto flex items-center justify-center h-14 w-14 rounded-full bg-orange-100 dark:bg-orange-900/30 mb-4">
                                <Mail className="h-7 w-7 text-orange-600 dark:text-orange-400" />
                            </div>
                            <h3 className="text-xl font-bold text-gray-900 dark:text-white">Recuperar Contraseña</h3>
                            <p className="text-sm text-gray-500 dark:text-gray-400 mt-2">
                                Ingresa tu correo electrónico y te enviaremos una contraseña temporal.
                            </p>
                        </div>
                        <form onSubmit={handleSubmit} className="space-y-5">
                            <Input
                                label="Email registrado"
                                type="email"
                                value={email}
                                onChange={(e) => setEmail(e.target.value)}
                                placeholder="ejemplo@restaurante.com"
                                required
                                leftIcon={<Mail className="h-4 w-4" />}
                            />
                            
                            {errorMessage && (
                                <div className="p-3 bg-red-50 dark:bg-red-900/20 text-red-700 dark:text-red-300 rounded-lg text-sm flex items-center gap-2">
                                    <AlertTriangle className="h-4 w-4 shrink-0" />
                                    {errorMessage}
                                </div>
                            )}

                            <Button
                                type="submit"
                                isLoading={isLoading}
                                className="w-full"
                                rightIcon={<ArrowRight className="h-4 w-4" />}
                            >
                                Generar Contraseña Temporal
                            </Button>
                        </form>
                    </>
                ) : (
                    <div className="text-center py-4">
                        <div className="mx-auto flex items-center justify-center h-14 w-14 rounded-full bg-green-100 dark:bg-green-900/30 mb-4 animate-bounce">
                            <CheckCircle className="h-7 w-7 text-green-600 dark:text-green-400" />
                        </div>
                        <h3 className="text-xl font-bold text-gray-900 dark:text-white">¡Contraseña Generada!</h3>
                        <p className="text-sm text-gray-500 dark:text-gray-400 mt-2 mb-6">
                            Usa la siguiente contraseña temporal para acceder:
                        </p>
                        
                        {tempPassword && (
                            <div className="bg-gray-100 dark:bg-gray-700 p-4 rounded-lg mb-8 border border-gray-300 dark:border-gray-600">
                                <p className="text-xs text-gray-500 dark:text-gray-400 uppercase font-bold mb-1 tracking-wider">Contraseña Temporal</p>
                                <p className="text-2xl font-mono font-bold text-gray-900 dark:text-white tracking-wider select-all">{tempPassword}</p>
                            </div>
                        )}

                        <Button
                            variant="secondary"
                            onClick={onClose}
                            className="w-full"
                        >
                            Volver al Login
                        </Button>
                    </div>
                )}
            </div>
        </div>
    );
};

const DatabaseSetupModal: React.FC<{ onClose: () => void }> = ({ onClose }) => {
    const { showToast } = useAppContext();

    const handleCopySql = () => {
        navigator.clipboard.writeText(SUPABASE_SCHEMA_SQL);
        showToast("Script SQL copiado al portapapeles.");
    };

    return (
        <div className="fixed inset-0 bg-black/60 z-50 flex items-center justify-center p-4" onClick={onClose}>
            <div className="bg-white dark:bg-gray-800 rounded-xl shadow-2xl w-full max-w-3xl max-h-[90vh] flex flex-col overflow-hidden" onClick={(e) => e.stopPropagation()}>
                <div className="p-5 border-b dark:border-gray-700 flex justify-between items-center bg-gray-50 dark:bg-gray-800">
                    <h3 className="font-bold text-lg text-gray-900 dark:text-white flex items-center gap-2">
                        <Database className="h-5 w-5 text-blue-600" /> Configuración de Base de Datos
                    </h3>
                    <button onClick={onClose} className="p-2 rounded-full hover:bg-gray-200 dark:hover:bg-gray-700 transition-colors"><X className="h-5 w-5" /></button>
                </div>
                <div className="p-6 overflow-y-auto bg-white dark:bg-gray-900">
                    <div className="bg-blue-50 dark:bg-blue-900/20 p-5 rounded-xl border border-blue-100 dark:border-blue-800 mb-6">
                        <p className="text-sm text-blue-800 dark:text-blue-300 font-bold mb-2 flex items-center gap-2">
                            <AlertCircle className="h-4 w-4" /> Instrucciones para corregir errores:
                        </p>
                        <ol className="list-decimal list-inside text-sm text-blue-800 dark:text-blue-300 space-y-2 ml-1">
                            <li>Copia el script SQL que aparece abajo.</li>
                            <li>Ve a tu proyecto en Supabase &gt; <strong>SQL Editor</strong>.</li>
                            <li>Pega el código y haz clic en <strong>Run</strong>.</li>
                            <li className="mt-2 pt-2 border-t border-blue-200 dark:border-blue-700/50">
                                <span className="font-bold text-red-600 dark:text-red-400">Si persisten errores de columnas faltantes:</span>
                                <ul className="list-disc list-inside ml-5 mt-1 text-gray-700 dark:text-gray-300 opacity-90">
                                    <li>Ve a <strong>Settings (Engranaje)</strong> &gt; <strong>API</strong>.</li>
                                    <li>En la sección "Schema Cache", haz clic en <strong>Reload</strong>.</li>
                                </ul>
                            </li>
                        </ol>
                    </div>
                    
                    <div className="relative group">
                        <div className="absolute top-0 right-0 p-2 bg-gray-900/80 rounded-bl-lg rounded-tr-lg opacity-0 group-hover:opacity-100 transition-opacity z-10">
                             <button 
                                onClick={handleCopySql}
                                className="text-white text-xs font-bold flex items-center gap-1 hover:text-blue-300"
                            >
                                <Copy className="h-3 w-3" /> Copiar
                            </button>
                        </div>
                        <pre className="bg-gray-900 text-gray-300 p-4 rounded-lg text-xs font-mono overflow-x-auto h-80 border border-gray-700 shadow-inner">
                            {SUPABASE_SCHEMA_SQL}
                        </pre>
                    </div>
                </div>
                <div className="p-4 bg-gray-50 dark:bg-gray-800 border-t dark:border-gray-700 flex justify-end">
                     <Button onClick={onClose} variant="secondary">
                        Cerrar
                    </Button>
                </div>
            </div>
        </div>
    );
};

export const LoginPage: React.FC = () => {
  const { login } = useAppContext();
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [showPassword, setShowPassword] = useState(false);
  const [isForgotModalOpen, setIsForgotModalOpen] = useState(false);
  const [isDbSetupOpen, setIsDbSetupOpen] = useState(false);
  const [loginError, setLoginError] = useState<string | null>(null);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoginError(null);
    if (!email || !password) return;
    setIsLoading(true);

    const success = await login(email, password);
    if (!success) {
        setLoginError("La contraseña no coincide o el usuario no existe.");
    }
    setIsLoading(false);
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-100 dark:bg-gray-900 p-4 transition-colors duration-300">
      <div className="w-full max-w-md bg-white dark:bg-gray-800 rounded-3xl shadow-2xl overflow-hidden transform transition-all hover:scale-[1.01]">
        <div className="p-10">
            <div className="text-center mb-8">
                <div className="inline-flex justify-center items-center p-4 bg-orange-100 dark:bg-orange-900/30 rounded-full mb-4 shadow-inner">
                    <Pizza className="h-12 w-12 text-orange-600 dark:text-orange-500" />
                </div>
                <h1 className="text-4xl font-extrabold text-gray-900 dark:text-white tracking-tight">Restaurante Pro</h1>
                <p className="mt-2 text-gray-500 dark:text-gray-400">Gestión integral para tu negocio gastronómico</p>
                
                <button 
                    onClick={() => setIsDbSetupOpen(true)}
                    className="mt-4 inline-flex items-center gap-2 px-3 py-1 bg-blue-50 hover:bg-blue-100 dark:bg-blue-900/20 dark:hover:bg-blue-900/40 border border-blue-200 dark:border-blue-800 text-blue-700 dark:text-blue-300 rounded-full text-xs font-semibold transition-colors"
                >
                    <Database className="h-3 w-3" /> Estado DB: Conectado
                </button>
            </div>

            <form onSubmit={handleSubmit} className="space-y-6">
            <Input
                id="email"
                name="email"
                type="email"
                label="Correo Electrónico"
                placeholder="admin@restaurante.com"
                value={email}
                onChange={(e) => { setEmail(e.target.value); setLoginError(null); }}
                disabled={isLoading}
                leftIcon={<Mail className="h-4 w-4" />}
                required
            />

            <div>
                <Input
                    id="password"
                    name="password"
                    type={showPassword ? "text" : "password"}
                    label="Contraseña"
                    placeholder="••••••••"
                    value={password}
                    onChange={(e) => { setPassword(e.target.value); setLoginError(null); }}
                    disabled={isLoading}
                    leftIcon={<Lock className="h-4 w-4" />}
                    rightElement={
                        <button
                            type="button"
                            onClick={() => setShowPassword(!showPassword)}
                            className="text-gray-400 hover:text-gray-600 dark:hover:text-gray-300 focus:outline-none transition-colors"
                            tabIndex={-1}
                        >
                            {showPassword ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
                        </button>
                    }
                    required
                />
                <div className="flex justify-end mt-2">
                    <button 
                        type="button" 
                        onClick={() => setIsForgotModalOpen(true)}
                        className="text-xs font-medium text-orange-600 hover:text-orange-500 hover:underline transition-colors"
                    >
                        ¿Olvidaste tu contraseña?
                    </button>
                </div>
            </div>

            {loginError && (
                <div className="flex items-center p-4 text-sm text-red-800 border border-red-200 rounded-xl bg-red-50 dark:bg-red-900/20 dark:text-red-300 dark:border-red-800/50 animate-fade-in-down" role="alert">
                    <AlertCircle className="flex-shrink-0 inline w-5 h-5 mr-3" />
                    <span className="font-medium">Error:</span>&nbsp;{loginError}
                </div>
            )}

            <Button
                type="submit"
                className="w-full py-3.5 text-base shadow-lg hover:shadow-orange-500/30"
                isLoading={isLoading}
                size="lg"
                rightIcon={!isLoading && <ArrowRight className="h-5 w-5" />}
            >
                Iniciar Sesión
            </Button>
            </form>
        </div>
        
        <div className="bg-gray-50 dark:bg-gray-700/30 p-4 text-center border-t border-gray-100 dark:border-gray-700">
            <p className="text-xs text-gray-500 dark:text-gray-400">
                &copy; {new Date().getFullYear()} Restaurante Pro 2.0. Todos los derechos reservados.
            </p>
        </div>
      </div>
      
      {isForgotModalOpen && <ForgotPasswordModal onClose={() => setIsForgotModalOpen(false)} />}
      {isDbSetupOpen && <DatabaseSetupModal onClose={() => setIsDbSetupOpen(false)} />}
    </div>
  );
};
